
require('./assets/script/bright');
require('./assets/script/dialog/OrangeDialog');
require('./assets/script/dialog/PlanetDialog');
require('./assets/script/dialog/PurpleDialog');
require('./assets/script/dialog/RocketDiaolg');
require('./assets/script/dialog/SpiritDialog');
require('./assets/script/dialog/SummerDialog');
require('./assets/script/dialog/YellowDialog');
require('./assets/script/flower');
require('./assets/script/prefeb/newhand');
require('./assets/script/sunset');
require('./assets/script/tool/amuseControl');
require('./assets/script/tool/amuseGameData');
require('./assets/script/tool/amuseResBind');
require('./assets/script/tool/amuseResUtil');
require('./assets/script/tool/amuseScroll');
require('./assets/script/tool/amuseSoundTool');
require('./assets/script/tool/amuseStorage');
