
require('./assets/script/cup');
require('./assets/script/dialog/AmeliaPop');
require('./assets/script/dialog/AvaPop');
require('./assets/script/dialog/EmilyPop');
require('./assets/script/dialog/EvelynPop');
require('./assets/script/dialog/IsabellaPop');
require('./assets/script/dialog/MiaPop');
require('./assets/script/dialog/SophiaPop');
require('./assets/script/flask');
require('./assets/script/glass');
require('./assets/script/prefeb/newhand');
require('./assets/script/tool/princessControl');
require('./assets/script/tool/princessGameData');
require('./assets/script/tool/princessResBind');
require('./assets/script/tool/princessResUtil');
require('./assets/script/tool/princessScroll');
require('./assets/script/tool/princessSoundTool');
require('./assets/script/tool/princessStorage');
